### ISSUE TITLE
saveAs should save to subfolder

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/http-extractor#11]
Narazil jsem na to až před pár dny. Když zadám `saveAs` třeba `mojetabulka`, ale stahovanej soubor je archiv, tak potom `processor-decompress` nezabere, protože ten detekuje archivy podle přípony. 

Jsou teď 2 řešení

a) `saveAs` jen vytvoří v `out/files` složku a staženej soubor beze změny jména stáhne do ní
b) `saveAs` parametr se nepoužije a použije se navrhovanej update v `processor-move-files` (https://github.com/keboola/processor-move-files/issues/7)

**Comment by odinuv** [comment]
b), coz me pripomina, ze by se to melo zavacasu udelat i na ty s3?

**Comment by ondrejhlavacek** [comment]
@odinuv tam už bych to nechal a), je to tam implementovaný a už jsou existující konfigurace, který to může rozbít.

**Comment by ondrejhlavacek** [comment]
@odinuv jak o tom vlastně přemejšlim, tak je to asi zpětně kompatibilní! když se nepoužije `saveAs` (udělám ho u S3 nepovinný), tak se tam nahodí move-files processor. good point.

**Comment by tomasfejfar** [comment]
Já, jestli to chápu správně, si myslím:

- `saveAs` je zodpovědnost uživatele. Pokud to chci jako archiv, tak tomu mám dát správnou příponu - to chování je vlastnost, ne chyba
- `processor-decompress` by mohl potenciálně archivy poznávat podle mime typu a ne podle přípony, ale veskrze je to opět zodpovědnost uživatele, aby si tam poslal smysluplná data. Ale ten mime typ by tomu mohl pomoct (ale na druhou stranu zas určitě zanese edge-case bugy)

**Comment by ondrejhlavacek** [comment]
Hm, ten mime-type mě nenapadl. Poválím to v hlavě ještě :-) Funkcionalitu typu `saveAs` budeme z komponent dávat ven a bude to řešit procesor. Že je název zodpovědnost uživatele, souhlas. Teď tam je jen jedna zkratka, a to, že název souboru je určující pro název vytvářené tabulky ve Storage. `.zip` nakonci to rozbije (nevalidní název tabulky), ale zároveň dekomprese to tam potřebuje.

Možná by mohl v manifestu být požadovanej název tabulky? cc @odinuv

**Comment by odinuv** [comment]
mime-typ nemame a detect na content je takovej divnej, zkusil jsem to udelat tak, aby to fungovalo i bez extension https://github.com/keboola/processor-decompress/pull/4 ale nejak happy z toho taky nejsem

**Comment by odinuv** [comment]
@ondrejhlavacek porad je tech konfiguraci par a porad jeste to neni public, takze jestli je moznost to vyhodit tak to vyhodme hned nez se s tim tahnout dalsich x let

**Comment by ondrejhlavacek** [comment]
můžu to tady zavřít, vyřešilo se to úpravou procesoru a v UI

**Comment by tomasfejfar** [comment]
Nemělo by se stejně `saveAs` zrušit? A místo něj dát processor?

**Comment by ondrejhlavacek** [comment]
Jo, v UI to tak je, `saveAs` je nepovinný, takže tomu nic nebránilo.

**Comment by tomasfejfar** [comment]
Ale dává smysl ho odebrat, pokud je nepovinné a nepoužívá se, ne?

**Comment by tomasfejfar** [comment]
Než se to pustí ven...

**Comment by ondrejhlavacek** [comment]
Ok!

**Comment by tomasfejfar** [comment]
Chápu správně, že prostě jen odstraním veškeré odkazy na saveAs?

**Comment by ondrejhlavacek** [comment]
jj
