### ISSUE TITLE
TooManyRedirects should be user error

### ISSUE THREAD

**Issue by Halama** [keboola/http-extractor#17]
`Fatal error: Uncaught GuzzleHttp\\Exception\\TooManyRedirectsException: Will not follow more than 5 redirects in`

https://connection.keboola.com/admin/utils/logs?file=2018/05/27/22/2018-05-27-22-07-19-5b0b0ff71d1ef-exception

**Comment by MiroCillik** [comment]
Myslim, ze tuto chybu to hodi, ked je nejaky problem na strasne serveru, pomohlo by implementovat exp. backoff. A ked to na niekolko pokusov neda, tak potom to vyhodit userovi na oci :)
