### ISSUE TITLE
Aborting retry as this error is permanent

### ISSUE THREAD

**Issue by odinuv** [keboola/http-extractor#29]
soubor to stahne, nefailne to, ale stejne to tam pise

![image](https://user-images.githubusercontent.com/4319320/52968823-bc6b8580-33ae-11e9-913e-9fb941661b12.png)

**Comment by tomasfejfar** [comment]
Máš to někde zreplikované? Nebo to dělá všude?

**Comment by odinuv** [comment]
afaik to dela vsude

**Comment by odinuv** [comment]
je toho plnej PT
