### ISSUE TITLE
Create abstract config class and use it on HTTP extractor

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/http-extractor#3]
> Ty gettery jsou proto, aby sis nemusel pamatovat klíče pole a nemohl v nich udělat typo.
>
> Jako ideálně by to byla knihovna.
> 
> Uživatel by si udělal Config extends KeboolaConfig. KeboolaConfig by byl abstraktní s metodou getConfigDefinition(): ConfigurationInterface, ze které by se vytahla ta secka toho konfiguráku a použila se v konstruktoru pro ověření. K tomu by byl abstraktní KeboolaConfigDefinition, který by měl v sobě základní strukturu toho keboolího configu (celého). A obsahoval by protected getParametersDefinition(), getStorageInput a getStorageOutput - tak aby šly přetížit, pokud je někdo potřebuje nějak konkrétně specifikovat (případně by mohly být abstraktní + privátní getDefaultStorageInput() pokud člověk nechce nic měnit. A nakonec ConfigLoader, který by měl loadConfig($path, Config::class) z cesty by natahnul JSON, ten zkontroloval, dekódoval a udělal z něj config. Uživatel by pak jen doimplementoval convenience gettery, aby mu to napovídalo datové typy a metody a nemusel si pamatovat klíče pole.

Ref. https://github.com/keboola/http-extractor/pull/1#discussion_r165025834

**Comment by odinuv** [comment]
Mela by to byt samostatna knihovna a implementovat +- stejny interface jako ty existujici pro R/Python  https://github.com/keboola/python-docker-application a https://github.com/keboola/r-docker-application

**Comment by tomasfejfar** [comment]
Closed by #6
