### ISSUE TITLE
Trailing forwardslash?

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/http-extractor#9]
Pokud není na konci `baseUrl` nebo na začátku `path` forwardslash, tak to spojí dohromady a vyfailuje to. Mohlo by se to pořešit v UI, ale taky by to možná mohl ošetřit přímo extraktor?

**Comment by ondrejhlavacek** [comment]
Stejná situace nastane, pokud forwardslash bude i v `baseUrl` i v `path` naráz.

**Comment by tomasfejfar** [comment]
Přesně proto jsem chtěl ty PathUtils... IMHO je nejsprávnější postup tohle řešit v kódu

- vezmu první, z toho osekám koncové lomítko (nebo backslash)
- vezmu poslední, z toho osekám začáteční lomítko (nebo backslash)
- zbytek osakám z obou stran
- celé to joinu pomocí `/`

A je pak úplně jedno, co do toho kdo pošle.

**Comment by ondrejhlavacek** [comment]
No ideálně, ale žádná z těch knihoven, o kterejch jsme se bavili, tohle nijak snadno nedělá. Všude to musíš předem atomizovat (a když už to máš, tak je to v podstatě hotový), tady ještě navíc přibývá URL + HTTP/HTTPS.

**Comment by tomasfejfar** [comment]
Ale tenhle postup by měl fungovat na všechno, ne? Pokud tam teda nepošleš samostatně `https://` na tom si to vyláme zuby, logicky. Podle těch kroků nahoře:

```
https://www.google.com/ | /compressed/ | /assets/favicon.ico
-> 
https://www.google.com | /compressed/ | /assets/favicon.ico
-> 
https://www.google.com | /compressed/ | assets/favicon.ico
-> 
https://www.google.com | compressed | assets/favicon.ico
->
https://www.google.com + / + compressed + / + assets/favicon.ico
```

**Comment by ondrejhlavacek** [comment]
Jj, přesně, ten postup je správně.

**Comment by odinuv** [comment]
a co `parse_url` - split path `/` - join everything `/` ?

**Comment by tomasfejfar** [comment]
`parse_url` mi to rozseká moc a pak bych musel ještě o něco složitějším kódem zas všechno poskládat dohromady :/
